# Generated by Django 3.2.4 on 2021-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=300, null=True, verbose_name='TITLE'),
        ),
    ]
